apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    basicAuth: false
    isDefault: true
    jsonData:
      defaultDatabase: ${CLICKHOUSE_DB}
      host: clickhouse
      port: 8123
      protocol: http
      username: ${CLICKHOUSE_USER}
      secure: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    editable: false
