{
 "title": "1C Event Log - Top Errors",
 "tags": [
  "1c",
  "event-log",
  "errors"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "infobase",
    "query": "SELECT DISTINCT infobase_name FROM logs.event_log WHERE infobase_name != '' AND level IN ('Error', 'Warning') ORDER BY infobase_name"
   },
   {
    "name": "user",
    "query": "SELECT DISTINCT user_name FROM logs.event_log WHERE user_name != '' AND level IN ('Error', 'Warning') ORDER BY user_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Top Errors Table",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  event_presentation AS \"Событие\",\n  user_name AS \"Пользователь\",\n  computer AS \"Компьютер\",\n  metadata_presentation AS \"Метаданные\",\n  comment AS \"Комментарий\",\n  count() AS \"Количество повторений\",\n  max(event_time) AS \"Последнее появление\"\nFROM logs.event_log\nWHERE $__timeFilter(event_time)\n  AND level IN ('Error', 'Warning')\n  AND ($infobase = '$__all' OR infobase_name IN ($infobase))\n  AND ($user = '$__all' OR user_name IN ($user))\nGROUP BY\n  event_presentation,\n  user_name,\n  computer,\n  metadata_presentation,\n  comment\nORDER BY \"Количество повторений\" DESC\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Errors by Event Type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  event_presentation AS event,\n  count() AS count\nFROM logs.event_log\nWHERE $__timeFilter(event_time)\n  AND level IN ('Error', 'Warning')\n  AND ($infobase = '$__all' OR infobase_name IN ($infobase))\n  AND ($user = '$__all' OR user_name IN ($user))\nGROUP BY event\nORDER BY count DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Errors by User",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  user_name AS user,\n  count() AS count\nFROM logs.event_log\nWHERE $__timeFilter(event_time)\n  AND level IN ('Error', 'Warning')\n  AND ($infobase = '$__all' OR infobase_name IN ($infobase))\n  AND ($user = '$__all' OR user_name IN ($user))\n  AND user_name != ''\nGROUP BY user\nORDER BY count DESC\nLIMIT 10"
    }
   ]
  }
 ]
}